#!/usr/bin/env python3
"""Deploy RAG-as-a-Service to Cloud Run.

Usage:
    python deployment/deploy_cloudrun.py
"""

import os
import sys
import json
import subprocess
from pathlib import Path


def print_info(msg: str):
    """Print info message."""
    print(f"[INFO] {msg}")


def print_success(msg: str):
    """Print success message."""
    print(f"[SUCCESS] {msg}")


def print_error(msg: str):
    """Print error message."""
    print(f"[ERROR] {msg}", file=sys.stderr)


def run_command(cmd: list[str], check: bool = True) -> subprocess.CompletedProcess:
    """Run shell command and return result."""
    result = subprocess.run(cmd, capture_output=True, text=True, check=False)
    
    if check and result.returncode != 0:
        print_error(f"Command failed: {' '.join(cmd)}")
        print_error(f"Error: {result.stderr}")
        raise subprocess.CalledProcessError(result.returncode, cmd, result.stdout, result.stderr)
    
    return result


def load_config() -> dict:
    """Load deployment configuration."""
    config = {}
    
    # Load from .env.deploy
    deploy_dir = Path(__file__).parent
    env_deploy_path = deploy_dir / '.env.deploy'
    
    if not env_deploy_path.exists():
        print_error("deployment/.env.deploy not found")
        sys.exit(1)
    
    with open(env_deploy_path) as f:
        for line in f:
            if '=' in line and not line.strip().startswith('#'):
                key, value = line.strip().split('=', 1)
                config[key] = value.strip('"')
    
    # Load from .env (generated by setup_infrastructure.py)
    env_path = deploy_dir.parent / '.env'
    if not env_path.exists():
        print_error(".env not found - run setup_infrastructure.py first")
        sys.exit(1)
    
    with open(env_path) as f:
        for line in f:
            if '=' in line and not line.strip().startswith('#'):
                key, value = line.strip().split('=', 1)
                config[key] = value.strip('"')
    
    # Validate required fields
    required = [
        'GCP_PROJECT_ID', 'GCP_REGION', 'GCS_BUCKET',
        'DATABASE_URL', 'CLOUD_SQL_CONNECTION_NAME', 'SERVICE_ACCOUNT_EMAIL'
    ]
    missing = [k for k in required if not config.get(k)]
    if missing:
        print_error(f"Missing configuration: {', '.join(missing)}")
        sys.exit(1)
    
    # Set defaults from .env.deploy
    config.setdefault('CLOUD_RUN_SERVICE', 'rag-api')
    config.setdefault('CLOUD_RUN_MEMORY', '1Gi')
    config.setdefault('CLOUD_RUN_CPU', '1')
    config.setdefault('CLOUD_RUN_MIN_INSTANCES', '0')
    config.setdefault('CLOUD_RUN_MAX_INSTANCES', '10')
    config.setdefault('CLOUD_RUN_TIMEOUT', '300')
    config.setdefault('CLOUD_RUN_CONCURRENCY', '80')
    
    return config


def build_and_deploy(config: dict) -> str:
    """Build container and deploy to Cloud Run."""
    project_id = config['GCP_PROJECT_ID']
    region = config['GCP_REGION']
    service_name = config['CLOUD_RUN_SERVICE']
    
    print_info(f"Building and deploying to Cloud Run...")
    print_info(f"  Project: {project_id}")
    print_info(f"  Region: {region}")
    print_info(f"  Service: {service_name}")
    
    # Prepare environment variables
    env_vars = [
        f"GCP_PROJECT_ID={config['GCP_PROJECT_ID']}",
        f"GCP_REGION={config['GCP_REGION']}",
        f"GCS_BUCKET={config['GCS_BUCKET']}",
        f"DATABASE_URL={config['DATABASE_URL']}",
        f"VERTEX_AI_LOCATION={config.get('VERTEX_AI_LOCATION', region)}",
        f"EMBEDDING_MODEL={config.get('EMBEDDING_MODEL', 'text-embedding-005')}",
        f"EMBEDDING_DIMENSION={config.get('EMBEDDING_DIMENSION', '768')}",
    ]
    
    # Build command
    cmd = [
        'gcloud', 'run', 'deploy', service_name,
        '--source', '.',
        '--platform', 'managed',
        '--region', region,
        '--allow-unauthenticated',
        '--service-account', config['SERVICE_ACCOUNT_EMAIL'],
        '--add-cloudsql-instances', config['CLOUD_SQL_CONNECTION_NAME'],
        '--memory', config['CLOUD_RUN_MEMORY'],
        '--cpu', config['CLOUD_RUN_CPU'],
        '--min-instances', config['CLOUD_RUN_MIN_INSTANCES'],
        '--max-instances', config['CLOUD_RUN_MAX_INSTANCES'],
        '--timeout', config['CLOUD_RUN_TIMEOUT'],
        '--concurrency', config['CLOUD_RUN_CONCURRENCY'],
        '--project', project_id
    ]
    
    # Add environment variables
    for env_var in env_vars:
        cmd.extend(['--set-env-vars', env_var])
    
    print_info("Deploying to Cloud Run (this takes 3-5 minutes)...")
    result = run_command(cmd)
    
    # Parse service URL from output
    for line in result.stdout.split('\n'):
        if 'Service URL:' in line or 'https://' in line:
            service_url = line.split()[-1]
            if service_url.startswith('https://'):
                return service_url
    
    # Fallback: get service URL
    result = run_command([
        'gcloud', 'run', 'services', 'describe', service_name,
        '--region', region,
        '--format', 'value(status.url)',
        '--project', project_id
    ])
    
    return result.stdout.strip()


def test_deployment(service_url: str):
    """Test deployed service."""
    print_info("Testing deployment...")
    
    # Test health endpoint
    import urllib.request
    
    health_url = f"{service_url}/health"
    try:
        with urllib.request.urlopen(health_url, timeout=10) as response:
            data = json.loads(response.read())
            if data.get('status') == 'healthy':
                print_success("Health check passed")
            else:
                print_error(f"Health check failed: {data}")
    except Exception as e:
        print_error(f"Health check failed: {e}")


def main():
    """Main deployment function."""
    print_info("RAG-as-a-Service Cloud Run Deployment")
    print_info("=" * 50)
    
    # Change to project root
    os.chdir(Path(__file__).parent.parent)
    
    # Load config
    config = load_config()
    print_success("Configuration loaded")
    
    # Build and deploy
    service_url = build_and_deploy(config)
    print_success(f"Deployed to: {service_url}")
    
    # Test deployment
    test_deployment(service_url)
    
    print_info("")
    print_success("Deployment complete!")
    print_info("")
    print_info(f"Service URL: {service_url}")
    print_info("")
    print_info("Test commands:")
    print_info(f"  curl {service_url}/health")
    print_info(f"  curl -X POST {service_url}/upload -F 'file=@document.pdf'")
    print_info("")


if __name__ == '__main__':
    main()
