#!/usr/bin/env python3
"""Local development - run FastAPI locally connecting to GCP infrastructure.

This script:
1. Loads configuration from .env (created by setup_infrastructure.py)
2. Starts Cloud SQL Proxy to connect to Cloud SQL
3. Runs FastAPI with hot reload

Usage:
    python deployment/local_run.py
"""

import os
import sys
import subprocess
import time
from pathlib import Path


def print_info(msg: str):
    print(f"[INFO] {msg}")


def print_success(msg: str):
    print(f"[SUCCESS] {msg}")


def print_error(msg: str):
    print(f"[ERROR] {msg}", file=sys.stderr)


def check_gcloud_auth():
    """Check if gcloud ADC is configured."""
    result = subprocess.run([
        "gcloud", "auth", "application-default", "print-access-token"
    ], capture_output=True)
    
    return result.returncode == 0


def load_env():
    """Load environment from .env file."""
    project_root = Path(__file__).parent.parent
    env_file = project_root / ".env"
    
    if not env_file.exists():
        print_error(".env file not found")
        print_info("Run: python deployment/setup_infrastructure.py")
        sys.exit(1)
    
    env = {}
    with open(env_file) as f:
        for line in f:
            if "=" in line and not line.strip().startswith("#"):
                key, value = line.strip().split("=", 1)
                env[key] = value
    
    return env


def start_cloud_sql_proxy(connection_name: str):
    """Start Cloud SQL Proxy in background."""
    print_info(f"Starting Cloud SQL Proxy for {connection_name}...")
    
    # Check if cloud-sql-proxy is installed
    result = subprocess.run(["which", "cloud-sql-proxy"], capture_output=True)
    if result.returncode != 0:
        print_error("cloud-sql-proxy not installed")
        print_info("Install: brew install cloud-sql-proxy")
        print_info("Or: https://cloud.google.com/sql/docs/postgres/connect-instance-auth-proxy#install")
        sys.exit(1)
    
    # Check if already running
    result = subprocess.run(
        ["pgrep", "-f", f"cloud-sql-proxy.*{connection_name}"],
        capture_output=True
    )
    if result.stdout.strip():
        print_success("Cloud SQL Proxy already running")
        return
    
    # Start proxy
    proxy_process = subprocess.Popen(
        ["cloud-sql-proxy", connection_name],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL
    )
    
    print_info("Waiting for Cloud SQL Proxy to be ready...")
    time.sleep(3)
    
    print_success("Cloud SQL Proxy started")


def create_local_env(config: dict):
    """Create .env.local with local DATABASE_URL."""
    project_root = Path(__file__).parent.parent
    env_local = project_root / ".env.local"
    
    # For local development, use localhost instead of /cloudsql/
    # Cloud SQL Proxy listens on localhost:5432 by default
    db_url = config["DATABASE_URL"]
    
    # Clean up asyncpg suffix first
    db_url_clean = db_url.replace("postgresql+asyncpg://", "postgresql://")
    
    # Replace /cloudsql/CONNECTION_NAME with localhost:5432
    if "/cloudsql/" in db_url_clean:
        # Extract user, password, database
        # Format: postgresql://user:pass@/dbname?host=/cloudsql/CONNECTION_NAME
        parts = db_url_clean.split("@/")
        if len(parts) == 2:
            user_pass = parts[0].replace("postgresql://", "")
            db_part = parts[1].split("?")[0]
            local_db_url = f"postgresql://{user_pass}@localhost:5432/{db_part}"
        else:
            local_db_url = db_url_clean
    else:
        local_db_url = db_url_clean
    
    env_content = f"""# Local Development Configuration
# Auto-generated by deployment/local_run.py
# Application runs locally, connects to GCP infrastructure

# Database (Cloud SQL via Proxy)
DATABASE_URL={local_db_url}

# GCP Configuration
GCP_PROJECT_ID={config['GCP_PROJECT_ID']}
GCP_REGION={config['GCP_REGION']}
GCS_BUCKET={config['GCS_BUCKET']}

# Vertex AI
VERTEX_AI_LOCATION={config.get('VERTEX_AI_LOCATION', config['GCP_REGION'])}
EMBEDDING_MODEL={config.get('EMBEDDING_MODEL', 'text-embedding-005')}
EMBEDDING_DIMENSION={config.get('EMBEDDING_DIMENSION', '1408')}

# FastAPI
PORT=8080
"""
    
    with open(env_local, "w") as f:
        f.write(env_content)
    
    print_success("Created .env.local for local development")
    return env_local


def run_fastapi(env_file: Path):
    """Run FastAPI with uvicorn."""
    project_root = Path(__file__).parent.parent
    
    print_info("")
    print_success("=" * 60)
    print_success("FastAPI Server Starting")
    print_success("=" * 60)
    print_info("")
    print_info("  🌐 URL:  http://localhost:8080")
    print_info("  📚 Docs: http://localhost:8080/docs")
    print_info("  🔄 Hot reload: enabled")
    print_info("  ☁️  Infrastructure: GCP (Cloud SQL + GCS + Vertex AI)")
    print_info("")
    print_info("Press Ctrl+C to stop")
    print_info("")
    
    # Set environment
    env = os.environ.copy()
    
    # Load .env.local
    with open(env_file) as f:
        for line in f:
            if "=" in line and not line.strip().startswith("#"):
                key, value = line.strip().split("=", 1)
                env[key] = value
    
    # Run uvicorn with hot reload
    # Use uvicorn from venv
    venv_python = project_root / ".venv" / "bin" / "python"
    if not venv_python.exists():
        print_error("Virtual environment not found")
        print_info("Create: python3 -m venv .venv && .venv/bin/pip install -r requirements.txt")
        sys.exit(1)
    
    subprocess.run([
        str(venv_python), "-m", "uvicorn",
        "src.main:app",
        "--host", "0.0.0.0",
        "--port", "8080",
        "--reload",
        "--reload-dir", "src"
    ], cwd=project_root, env=env)


def main():
    """Main function."""
    print_info("RAG-as-a-Service Local Development")
    print_info("=" * 60)
    print_info("Running locally, connecting to GCP infrastructure")
    print_info("")
    
    # Check gcloud auth
    if not check_gcloud_auth():
        print_error("gcloud Application Default Credentials not configured")
        print_info("Run: gcloud auth application-default login")
        sys.exit(1)
    print_success("gcloud ADC configured")
    
    # Load configuration
    config = load_env()
    print_success(f"Configuration loaded (Project: {config['GCP_PROJECT_ID']})")
    
    # Start Cloud SQL Proxy
    connection_name = config.get("CLOUD_SQL_CONNECTION_NAME")
    if connection_name:
        start_cloud_sql_proxy(connection_name)
    else:
        print_error("CLOUD_SQL_CONNECTION_NAME not found in .env")
        sys.exit(1)
    
    # Create local env
    env_file = create_local_env(config)
    
    # Run FastAPI
    try:
        run_fastapi(env_file)
    except KeyboardInterrupt:
        print_info("")
        print_info("Shutting down...")
        print_success("Stopped")


if __name__ == "__main__":
    main()
